version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: circleci/node:7.10 
        
jobs:
  wdio-test:
    environment:
      LT_USERNAME: varunkumarb
      LT_ACCESS_KEY: doLbtRzYpWdpD1xxcIQdByQ1b7kmqMNg43DrpsYwGxbPBtphNU
    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          npm install webdriverio
          npm i selenium-webdriver
          npm run single
          

workflows:
  my-custom-workflow:
    jobs:
      - wdio-test